export interface OfferupCategory {
  name: string;
  subcategories: string[];
}

export const OFFERUP_CATEGORIES: OfferupCategory[] = [
  {
    name: "Electronics & Media",
    subcategories: [
      "Audio & Speakers",
      "Cell phones & Accessories",
      "Cameras & Photography",
      "TVs & Media players",
      "Video games & Consoles",
      "Computers & Accessories",
      "Books, Movies, & Music",
      "Wearables",
      "Drones",
      "Virtual reality",
      "3D Printers & Supplies",
      "Other - Electronics & Media",
    ],
  },
  {
    name: "Home & Garden",
    subcategories: [
      "Furniture",
      "Household",
      "Appliances",
      "Kitchen & Dining",
      "Bathroom",
      "Tools & Machinery",
      "Home improvement",
      "Lawn & Garden",
      "Home decor",
      "Other - Home & Garden",
    ],
  },
  {
    name: "Clothing, Shoes, & Accessories",
    subcategories: [
      "Women's clothing",
      "Men's clothing",
      "Women's shoes",
      "Men's shoes",
      "Jewelry & Accessories",
      "Girls' clothing",
      "Boys' clothing",
      "Baby & Toddler girl clothing",
      "Baby & Toddler boy clothing",
      "Baby & Toddler accessories",
      "Girls' shoes",
      "Girls' accessories",
      "Boys' shoes",
      "Boys' accessories",
      "Other - Clothing, Shoes, & Accessories",
    ],
  },
  {
    name: "Baby & Kids",
    subcategories: [
      "Girls' accessories",
      "Boys' accessories",
      "Bathing & Skincare",
      "Car seats & Accessories",
      "Diapering",
      "Feeding",
      "Baby gear",
      "Health & Baby care",
      "Nursery furniture & Decor",
      "Potty training",
      "Pregnancy & Maternity",
      "Baby safety",
      "Strollers & Accessories",
      "Baby toys",
      "Other - Baby & Kids",
    ],
  },
  {
    name: "Vehicles",
    subcategories: [
      "Cars & Trucks",
      "Motorcycles",
      "Campers & RVs",
      "Boats & Marine",
      "Powersport vehicles",
      "Trailers",
      "Commercial vehicles",
      "Tires & Rims",
      "Auto parts & Accessories",
      "Other - Vehicles",
    ],
  },
  {
    name: "Toys, Games, & Hobbies",
    subcategories: [
      "Toys",
      "Games & Puzzles",
      "Outdoor toys & Games",
      "Stuffed animals & Plush",
      "Dress up & Pretend",
      "Trading cards",
      "Musical instruments",
      "Other - Toys, Games, & Hobbies",
    ],
  },
  {
    name: "Sports & Outdoors",
    subcategories: [
      "Exercise",
      "Yoga & Pilates",
      "Mixed martial arts & Boxing",
      "Bikes & Cycling",
      "Skateboarding",
      "Fishing",
      "Camping & Hiking",
      "Water sports",
      "Ice & Snow sports",
      "Lawn games",
      "Team sports",
      "Golf",
      "Fan shop",
      "Other - Sports & Outdoors",
    ],
  },
  {
    name: "Collectibles & Art",
    subcategories: [
      "Art",
      "Arts & Crafts supplies",
      "Antiques",
      "Collectibles",
      "Handmade",
      "Other - Collectibles & Art",
    ],
  },
  {
    name: "Pet supplies",
    subcategories: [
      "Pet collars & Leashes",
      "Pet clothing, Accessories, & Shoes",
      "Pet toys",
      "Pet feeding",
      "Pet bedding",
      "Pet furniture",
      "Pet carriers & Houses",
      "Pet health & Wellness",
      "Training",
      "Pet gates & Fences",
      "Other - Pet supplies",
    ],
  },
  {
    name: "Health & Beauty",
    subcategories: [
      "Hair care",
      "Bath & Body",
      "Makeup & Cosmetics",
      "Skincare",
      "Fragrance",
      "Personal care",
      "Tools & Accessories",
      "Other - Health & Beauty",
    ],
  },
  {
    name: "Wedding",
    subcategories: [
      "Jewelry",
      "Invitations & Paper",
      "Gifts & Mementos",
      "Decorations",
      "Accessories",
      "Clothing",
      "Shoes",
      "Other - Wedding",
    ],
  },
  {
    name: "Business equipment",
    subcategories: [
      "Farming & Agriculture",
      "Building materials & Supplies",
      "Cleaning & Janitorial supplies",
      "Electrical equipment & Supplies",
      "Facility maintenance & Safety",
      "Fasteners & Hardware",
      "HVAC",
      "Light industrial equipment & Tools",
      "Material handling",
      "Office equipment & Supplies",
      "Restaurant & Food service equipment",
      "Printing & Graphic arts",
      "Retail & Services",
      "Industrial fuel & Energy equipment",
      "Other - Business equipment",
    ],
  },
];

export function offerupSubcategories(category: string): string[] {
  return OFFERUP_CATEGORIES.find((c) => c.name === category)?.subcategories ?? [];
}
